securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

paths:
  /members:
    get:
      summary: My endpoint
      description: This endpoint requires authorization
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
    